last

diff --git a/install b/install
--- a/install
+++ b/install
@@ -11,11 +11,11 @@ env=latplan
         exit 1
     }
 
-    conda env create -n $env -f environment.yml || {
-        echo "installation failed; cleaning up"
-        conda env remove -n $env
-        exit 1
-    }
+    # conda env create -n $env -f environment.yml || {
+    #     echo "installation failed; cleaning up"
+    #     conda env remove -n $env
+    #     exit 1
+    # }
 
     conda activate $env
 
@@ -38,6 +38,8 @@ env=latplan
     conda env config vars set CPATH=${CONDA_PREFIX}/include:${CONDA_PREFIX}/x86_64-conda-linux-gnu/sysroot/usr/include:
     conda env config vars set ROSWELL_HOME=$(readlink -ef .roswell)
 
+
+
     # note: "variables" field in yaml file introduced in conda 4.9 does not work because it does not expand shell variables
 
     # these are required for the variables to take effect
@@ -45,7 +47,13 @@ env=latplan
 
     echo $CPATH ; echo $LD_LIBRARY_PATH
 
+
     conda env config vars list
+
+
+    echo "111111111111"
+
+    cmake -D CMAKE_C_COMPILER="/usr/bin/cc" -D CMAKE_CXX_COMPILER "/usr/bin/g++" /g100_work/uBS21_InfGer_0/latplan/downward/src
 
     ################################################################
     # build fast downward
@@ -54,6 +62,8 @@ env=latplan
         cd downward
         ./build.py -j $(cat /proc/cpuinfo | grep -c processor) release
     )
+
+    echo "22222222222222222"
 
     ################################################################
     # build ARRIVAL validator through roswell
@@ -67,8 +77,10 @@ env=latplan
         ros dynamic-space-size=8000 install numcl arrival eazy-gnuplot magicffi dataloader
     )
 
+    echo "3333333333"
+
     make -j 1 -C lisp
-    ./download-dataset.sh
+    # ./download-dataset.sh
 
 ) && {
     conda activate $env >/dev/null 2>/dev/null || echo "This script must be sourced, not executed. Run it like: source $0"
